"""Initial migration

Revision ID: 222bef142a6f
Revises: 
Create Date: 2025-04-15 04:54:47.237075

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '222bef142a6f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('concept_maps', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('concept_maps', schema=None) as batch_op:
        batch_op.drop_column('is_deleted')

    # ### end Alembic commands ###
