"""Add auth0_id to users

Revision ID: 3bb551ccbb9c
Revises: 455905f2033a
Create Date: 2025-04-17 19:57:38.045128

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3bb551ccbb9c'
down_revision = '455905f2033a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('auth0_id', sa.String(length=128), nullable=True))
        batch_op.create_unique_constraint(None, ['auth0_id'])
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.VARCHAR(length=256), nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('auth0_id')

    # ### end Alembic commands ###
