"""Fix constraint for auth0_id

Revision ID: 6e0d3b0a644f
Revises: 3bb551ccbb9c
Create Date: 2025-04-17 20:00:51.285125

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e0d3b0a644f'
down_revision = '3bb551ccbb9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('auth0_id', sa.String(length=128), nullable=True))
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.VARCHAR(length=256), nullable=False))
        batch_op.drop_column('auth0_id')

    # ### end Alembic commands ###
